FROM node:8.11-alpine

ENV LANG C.UTF-8

# add a simple script that can auto-detect the appropriate JAVA_HOME value
# based on whether the JDK or only the JRE is installed
RUN { \
		echo '#!/bin/sh'; \
		echo 'set -e'; \
		echo; \
		echo 'dirname "$(dirname "$(readlink -f "$(which javac || which java)")")"'; \
	} > /usr/local/bin/docker-java-home \
	&& chmod +x /usr/local/bin/docker-java-home
ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk
ENV PATH $PATH:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin

ENV JAVA_VERSION 8u191
ENV JAVA_ALPINE_VERSION 8.191.12-r0

RUN set -x \
	&& apk add --no-cache \
		openjdk8="$JAVA_ALPINE_VERSION" \
	&& [ "$JAVA_HOME" = "$(docker-java-home)" ]

RUN apk --update add git openssh && \
rm -rf /var/lib/apt/lists/* && \
rm /var/cache/apk/*

COPY ./agent.jar /jenkins/agent.jar
RUN mkdir -p /home/fyx

WORKDIR /jenkins
ENTRYPOINT [ "java", "-jar", "agent.jar", "-jnlpUrl", "http://192.168.0.34:8080/computer/npm/slave-agent.jnlp", "-secret", "714536e0af8982b5514f9ac8bf9ecfa8756ea1310bb55f13f8deaa2dbf398930", "-workDir", "'/home/fyx'"] 

